# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unittest:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7.3
      - image: circleci/mysql:5.7
      - image: redis:alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements/requirements.txt" }}
            - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip mycli
            pip install -U -r requirements/requirements-test.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements/requirements.txt" }}
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: create database
          command: |
            . venv/bin/activate
            mycli -u root -h 127.0.0.1 -e 'CREATE DATABASE trade;'
      - run:
          name: run tests
          command: |
            echo $PWD
            ls .
            . venv/bin/activate
            cd src/
            sh ../.test/runtest
          environment:
            DOTENV_PATH_FOR_DYNACONF: "data/etc/example.env"
            ENVVAR_PREFIX_FOR_DYNACONF: "false"
            DOTENV_OVERRIDE: "false"
            DATABASE_URI: "mysql://root:@127.0.0.1:3306/trade"
            REDIS_URI: "redis://localhost:6379/0"

workflows:
  version: 2
  UnitTest-DockerBuild-Deploy:
    jobs:
      - unittest
