# Generated by Django 2.1.13 on 2021-01-10 08:12

from django.db import migrations, models
import framework.database


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('platform_id', models.IntegerField(null=True)),
                ('nickname', models.CharField(max_length=255)),
                ('picture_url', models.URLField(max_length=512)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_enable', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('platform_owner', '平台属主'), ('user', '用户')], default='user', max_length=32)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'broadband_user',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('openid', models.CharField(max_length=255)),
                ('out_trade_no', models.CharField(max_length=255)),
                ('attach', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('total_fee', models.IntegerField()),
                ('appid', models.CharField(max_length=32)),
                ('mch_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('unpaid', 'UNPAID'), ('paid', 'PAID'), ('expired', 'EXPIRED')], default='unpaid', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_user_id', models.IntegerField()),
                ('ssid', models.CharField(default=None, max_length=255)),
                ('qrcode_url', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.CreateModel(
            name='ResourceChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('before', models.DateTimeField()),
                ('after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_change',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=255)),
                ('bind_platform_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('picture_url', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('openid',)},
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('owner_user_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('out_trade_no',)},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('username',), ('user_id', 'platform_id')},
        ),
    ]
