# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('openid', models.CharField(max_length=255)),
                ('out_trade_no', models.CharField(max_length=255, unique=True)),
                ('attach', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(default='', max_length=255)),
                ('total_fee', models.IntegerField()),
                ('appid', models.CharField(default='payjs', max_length=32)),
                ('mch_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('expired', '已过期')], default='unpaid', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
    ]
