# Generated by Django 2.1.13 on 2020-08-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
