# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.DateTimeField()),
                ('after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Orders')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trade.User')),
            ],
            options={
                'db_table': 'resource_change',
            },
        ),
    ]
