# Generated by Django 2.1.13 on 2021-01-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210110_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='qrcode_url',
            new_name='qrcode_content',
        ),
    ]
