# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180629_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('headimgurl', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weixin',
            },
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_enable',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='headimgurl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='openid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='user',
            name='weixin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade.Weixin'),
            preserve_default=False,
        ),
    ]
