# Generated by Django 2.1.13 on 2020-08-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200801_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadbandorder',
            name='uuid',
        ),
    ]
