# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_resourcechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_enable',
        ),
    ]
