# Generated by Django 2.1.13 on 2021-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20210110_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='picture_url',
        ),
        migrations.AlterField(
            model_name='account',
            name='platform_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
