# Generated by Django 2.1.13 on 2021-01-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20210110_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='owner_profit_percent',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
