# Generated by Django 2.1.13 on 2021-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_platform_owner_profit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
