# Generated by Django 2.1.13 on 2020-01-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixin',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
