# Generated by Django 2.1.13 on 2021-01-18 14:06

from django.db import migrations, models
import framework.field


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_order_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_id',
            field=framework.field.SnowFlakeField(null=True),
        ),
        migrations.AddField(
            model_name='resourcechange',
            name='out_trade_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=framework.field.SnowFlakeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('openid',), ('user_id',)},
        ),
    ]
