# Generated by Django 2.1.13 on 2021-01-18 13:32

from django.db import migrations, models
import framework.field


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_order_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_id',
            field=framework.field.SnowFlakeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcechange',
            name='out_trade_no',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=framework.field.SnowFlakeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('user_id',), ('openid',)},
        ),
    ]
