# Generated by Django 2.1.13 on 2021-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20210118_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='bind_platform_id',
            field=models.BigIntegerField(),
        ),
    ]
