# Generated by Django 2.1.13 on 2021-01-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20210118_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechange',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
