# Generated by Django 2.1.13 on 2021-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20210118_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.BigIntegerField(default=1351190574951043072),
        ),
        migrations.AlterField(
            model_name='resourcechange',
            name='out_trade_no',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=1351190574988791808),
        ),
    ]
