# Generated by Django 2.1.13 on 2021-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20210118_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.BigIntegerField(default=1351479249010167808),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=1351479249031139328),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('platform_id',), ('owner_user_id',)},
        ),
    ]
