# Generated by Django 2.1.13 on 2021-01-19 11:25

from django.db import migrations, models
import utils.snowflake


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20210119_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.BigIntegerField(default=utils.snowflake.new_id),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=utils.snowflake.new_id),
        ),
    ]
