# Generated by Django 2.1.13 on 2021-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20210119_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='owner_user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
