# Generated by Django 2.1.13 on 2021-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20210119_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
