# Generated by Django 2.1.13 on 2021-01-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_auto_20210119_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('platform_id',), ('owner_user_id',)},
        ),
    ]
