# Generated by Django 2.1.13 on 2021-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20210123_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'PLATFORM_OWNER'), ('user', 'USER')], default='user', max_length=32),
        ),
    ]
