# Generated by Django 2.1.13 on 2021-02-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_auto_20210204_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='radius_password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
