# Generated by Django 2.1.13 on 2021-02-27 14:58

from django.db import migrations, models
import framework.database


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_account_radius_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('radius_password', models.CharField(max_length=255)),
                ('is_enable', models.BooleanField(default=True)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mac_account',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.AlterUniqueTogether(
            name='macaccount',
            unique_together={('username',)},
        ),
    ]
