# Generated by Django 2.1.13 on 2021-02-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_auto_20210227_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaccount',
            name='updated_at',
        ),
    ]
