# Generated by Django 2.1.13 on 2021-03-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_remove_macaccount_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaccount',
            name='ap_mac',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
