# Generated by Django 2.1.13 on 2021-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_macaccount_ap_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaccount',
            name='ap_mac',
            field=models.CharField(max_length=24),
        ),
    ]
