# Generated by Django 2.1.13 on 2021-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0022_auto_20210304_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaccount',
            name='bind_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
