# Generated by Django 2.1.13 on 2021-03-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0023_macaccount_bind_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcechange',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='macaccount',
            name='bind_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
