# Generated by Django 2.1.13 on 2021-03-18 15:54

from django.db import migrations, models
import framework.database


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0024_auto_20210308_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatAp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_mac', models.CharField(max_length=24)),
                ('last_auth_user', models.CharField(max_length=255)),
                ('last_auth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stat_ap',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
        migrations.CreateModel(
            name='StatUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('user_mac', models.CharField(max_length=24)),
                ('ap_mac', models.CharField(max_length=24)),
                ('accept_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stat_user',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
    ]
