# Generated by Django 2.1.13 on 2021-03-28 10:26

from django.db import migrations, models
import framework.database


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0025_statap_statuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('ap_mac', models.CharField(max_length=24)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ap_owner',
            },
            bases=(models.Model, framework.database.BaseModel),
        ),
    ]
