# Generated by Django 2.1.13 on 2021-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_apowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apowner',
            name='remark',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
